# Generated by Django 4.2.7 on 2024-04-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbackoffer',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='cashbackoffer',
            name='expirationDate',
        ),
        migrations.RemoveField(
            model_name='cashbackoffer',
            name='limitations',
        ),
    ]
