# Generated by Django 4.2.7 on 2024-04-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usersms',
            options={},
        ),
    ]
